### PR TITLE
Fixing #17, adding --bitdepth flag and updated requirements

### PR DESCRIPTION
**Pull request by M0Rf30**

### CODE REVIEW

**Comment by M0Rf30** [comment]
With this PR you can create 2 channels wav files with a bitdepth of choice. accepted values by --bitdepth flag ( PCM_32, PCM_24, PCM_16)

**Comment by jaakkopasanen** [comment]
Thanks a lot! Couple of nitpicking things:

1. Bit depth is not a compound word so the parameter name should be `bit_depth`
2. CLI argument help says "Number of bits for every sample" while actually "PCM_16" like string is required. I would strongly prefer this to be actual integer of bits and conversion to SoundFile requiremets to be handled by the code.
3. `FrequencyResponse.impulse_response()` has now `bitdepth` as kwarg but is not used. Bit depth is a parameter in the WAV file write so this should be simply removed.

Other than these issues your pull request looks good. Fix the mentioned and I'll accept and merge.

**Comment by jaakkopasanen** [comment]
Fantastic! Thanks again for your contribution.

**Comment by M0Rf30** [comment]
Thanks to you man

**Pull request merged**
