### PR TITLE
FEAT: Server application

### PR DESCRIPTION
**Pull request by carlwilson**
This isn't really ready to go yet but I thought I'd try to work out if you're interested in something like this or not for now. I use your work a fair bit for personal listening through Roon. They have a large community who aren't all particularly tech-savvy who struggle to download and install the filters. I figured a web application might help them. This PR sets up a simple Flask web application driven by the available oratory1990 results. Currently, it just provides a searchable table where people can find their headphones and download a Roon friendly zipped package of the two available convolution filters. It's pretty basic with a few extra REST endpoints that have an eye on future direction.

If you're not keen to merge this, I totally understand. Just let me know and I'll tease it out into its own project. If you want to see it I have a test version up at <https://phones.killdozer.uk/>. There's no attribution for your great work there yet but that's next on my fix list today.

### CODE REVIEW

**Comment by jaakkopasanen** [comment]
Very cool to see things happening around AutoEq! Unfortunately I'm not sure how well this fits into the vision I have for AutoEq. Eventually I certainly intend to have a webapp for AutoEq where users can tweak all of the parameters without installing AutoEq on their own machine. I'd probably add this zip functionality there as well. However a server which only serves outputs, and only one kind at that, is not quite what I had in mind.

It might be better to split this into it's own project.

**Comment by carlwilson** [comment]
Hi @jaakkopasanen I understand but perhaps I should have been clearer regarding my intentions. This is really my MVP start. The PR isn't complete and I'm aiming to develop a "design your own filter" page quite shortly. This is just a couple of evenings work as I get to grips with the ideas. I suggest we close the PR for now and I come back when I've moved it forward some.

BTW I also have a Docker file for the CLI autoeq, which I'm using to generate my own "custom" filters, I prefer linear phase for example. Would a PR with that be of interest?

**Comment by JamesYeoman** [comment]
My issue #290 is arguably similar in intentions of this PR. It's a simpler approach, and for a system-wide equalisation option, but I'd be interested in your thoughts

**Review by horyek — APPROVED** [review]

**Review by sajidkalid — APPROVED** [review]

**Comment by jaakkopasanen** [comment]
It's been a long time but finally I finished not only server but also a full fledged web app for AutoEq. This of course means this PR can now be closed.

**Comment by carlwilson** [comment]
That's exciting, I'll check it out :) Good work @jaakkopasanen

**Pull request closed without merging**
