### PR TITLE
Update oratory1990's onear measurements and results

### PR DESCRIPTION
**Pull request by douglascamata**
This pull request updates the measurements and results for oratory1990's onear headphones.

I noticed that some results are not deterministic, i.e. for the oratory1990's measurement of `Superlux HD 662F (Brainwavz round XL pleather earpads)` headphone I get different results from running the processing over and over again. Seems like floating point math errors, because some numbers are off by +/- 0.01 dB. This requires some deeper investigation.

Note: no new headphone was added.

### CODE REVIEW

**Comment by douglascamata** [comment]
@jaakkopasanen this should be ready for your review now.

**Comment by douglascamata** [comment]
@eladri100 found some missing headphones as reported in https://github.com/jaakkopasanen/AutoEq/issues/427#issuecomment-1072624602. It seems to be due to a change in the false name for some equipment. I'll rerun the crawler and fix the name index.

**Comment by douglascamata** [comment]
All the headphones below had some naming changes and required a simple update to the name index through the crawler Jupyter notebook:

1. Beyerdynamic DT 250 (this is the 250 ohm version): ✅
2. Beyerdynamic T1 2nd Generation: ✅
3. Beyerdynamic T1 3rd Generation: ✅
4. Sony WH-1000XM2: ✅
5. Sony WH-1000XM3: ✅
6. Sony WH-1000XM4: ✅

These two below required some more tinkering. They were both explicitly ignored in the name index. So when I went through the process of removing results and measurements, crawling new measurements and generating new results, they were detected as "stale" measurements (no results were produced because of the "ignore" clause in the name index) and removed. I added them back to the name index.

7. Sennheiser "HD 25-1 II" (the bad seal version, the "HD25-1 II" good seal version is still there): ✅
8. Sennheiser HE 1 Orpheus 2: ✅

**Comment by mirh** [comment]
I'm afraid Jaakko hasn't been active for half a year...

**Comment by douglascamata** [comment]
Closing as an update was done in 647d0422ac346a5616eaf6ddda0420317121941b.

**Pull request closed without merging**
