### PR TITLE
Add rtings Google Pixel Buds Pro

### PR DESCRIPTION
**Pull request by diamondburned**
What I did:

```sh
python -m measurements.rtings.rtings_crawler
python -m results.update_results --rtings --inear --new_only
```

### CODE REVIEW

**Comment by diamondburned** [comment]
As a side note, I had to make this adjustment to get `chromedriver` working with the program:

```diff
diff --git a/measurements/rtings/rtings_crawler.py b/measurements/rtings/rtings_crawler.py
index fc2b20663d..631ab9f3eb 100644
--- a/measurements/rtings/rtings_crawler.py
+++ b/measurements/rtings/rtings_crawler.py
@@ -29,7 +29,7 @@ class RtingsCrawler(Crawler):
         if driver is None:
             opts = Options()
             opts.add_argument('--headless')
-            driver = webdriver.Chrome(os.path.abspath(os.path.join(DIR_PATH, '..', 'chromedriver')), options=opts)
+            driver = webdriver.Chrome('chromedriver', options=opts)
         super().__init__(driver=driver)
 
     @staticmethod
```

This understandably breaks the "needs chromedriver in measurements/" thing, but it's what I had to do to get it to see my `$PATH`.

**Comment by diamondburned** [comment]
Also as a side note: a `shell.nix` file for future use:

```nix
{ pkgs ? import <nixpkgs> {} }:

let deps = 
	(with pkgs; [
		python3 ghostscript chromedriver chromium cairo libsndfile
	]) ++
	(with pkgs.python3.pkgs; [
		pillow pandas matplotlib scipy numpy wheel tensorflowWithoutCuda pycairo soundfile
	]);

in pkgs.mkShell {
	name = "AutoEq";

	buildInputs = deps;

	MPLBACKEND = "cairo";

	shellHook = ''
		# Tells pip to put packages into $PIP_PREFIX instead of the usual locations.
		# See https://pip.pypa.io/en/stable/user_guide/#environment-variables.
		export PIP_PREFIX=$(pwd)/_build/pip_packages
		export PYTHONPATH="$PIP_PREFIX/${pkgs.python3.sitePackages}:$PYTHONPATH"
		export PATH="$PIP_PREFIX/bin:$PATH"
		unset SOURCE_DATE_EPOCH
		source .venv/bin/activate
		# Python has to be the worst fucking language to deal with.
		LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${pkgs.lib.makeLibraryPath deps}
	'';
}
```

**Comment by Slava848** [comment]
> # - [ ] - - []()__

**Comment by Slava848** [comment]
# > # - [ ] - - []()__

**Comment by douglascamata** [comment]
@jaakkopasanen you might want to delete the comments made by this `Slava848`. This looks like an attempt to trigger something, like a bug, somewhere.

**Comment by diamondburned** [comment]
It seems like these measurements were added without merging this PR. Since that fixes it, I'll just close this PR.

**Pull request closed without merging**
