### PR TITLE
Add tutorial for applying eq only using pipewire

### PR DESCRIPTION
**Pull request by bradyhaley**
I'm not sure about the quality of the pipewire convolver. But it seems to work fine, and fast.

### CODE REVIEW

**Comment by jaakkopasanen** [comment]
Is there a benefit of using Pipewire's convolver versus installing EasyEffects? This doesn't seem to me like a more convenient way.

**Comment by fn2006** [comment]
EasyEffects 6.X is only available as a flatpak on Debian-based distros and I experience frequent crashes that don't happen on the 5.X Debian package but EasyEffects 6.X doesn't build on Debian-based distros.

**Comment by bradyhaley** [comment]
EasyEffects does seem convenient. But the program is very unstable for me, it has many memory leaks, and it can't  even hide to systray.

**Comment by PoorPocketsMcNewHold** [comment]
In addition, you just remove one application in the process.

**Comment by xaionaro** [comment]
Just want to:
1. Say thanks to @bradyhaley : EasyEffects also crashes on my computer as well, so I cannot trust it and use for important stuff (like my main audio sink); so thanks for sharing your config for autoeq in Linux. It didn't work well for me, though: just no audio, when I enable this filter; but yet it is useful to have examples of others.
2. Leave a comment that: for anybody also struggling, and for whom @bradyhaley 's solution does not work as well: I also made another solution here: https://github.com/xaionaro-go/equalizer-easyeffects2pipewire 

P.S.: @jaakkopasanen : EasyEffects is very heavy and unstable; IMO, the majority of audiophiles in Linux would not use it as the main audio sink.

**Pull request closed without merging**
