### PR TITLE
Make autoeq use a configurable amount of threads

### PR DESCRIPTION
**Pull request by douglascamata**
This PR improves on the work added in #491, which ended up reverted in #492 as it by default was using all threads available and consuming a lot of memory.

The improvements done were:

- The amount of threads used is now configurable via the `--thread_count` arg of the `autoeq.py` script.
- By default, the amount of threads used is **1**, so the behavior doesn't change.
- If `--thread_count` is set to `"max"`, the script will automatically use all the available threads.

It's important to be aware that the more threads are used, the more memory the whole process will take.

### CODE REVIEW

**Comment by douglascamata** [comment]
Done with the improvements we talked about, @jaakkopasanen 👍

**Comment by jaakkopasanen** [comment]
Better, but still consumes all memory even when using only 2 threads. The process consumes less than 1 GB of memory with one thread so looks like it's not a problems of N threads consuming N times the memory. I won't revert this though, since it works as before with the default value.

I'm on Windows 10 and tested using Python 3.10 and Tensorflow 2.9 and 2.8. However, when I switched to Python 3.8 and Tensorflow 2.3 everything whent just smoothly, even with `--thread_count=max`. I then tested with Python 3.8 and Tensorflow 2.9 and the process failed again. Testing different versions of Tensorflow revealed that the maximum version which still works is 2.3.

Python 3.9 and 3.10 don't support Tensorflow 2.3 and I'd prefer not to stay with old versions of Python and Tensorflow forever, especially since Tensorflow 2.3 doesn't install on the ARM Macs. Would you mind debugging this on your end to see if you can make it work on Python 3.10 and Tensorflow 2.9?

I tested with this command
```
python autoeq.py --input_dir="measurements/oratory1990/data/inear" --output_dir="my_results/oratory1990" --compensation="compensation/harman_in-ear_2019v2.csv" --equalize --parametric_eq --max_filters=10 --thread_count 1
```

**Comment by douglascamata** [comment]
I'll try it out and report my results. I've got an ARM Mac and a Windows 11 machine (where I use WSL2) at my disposal for tests. 

I've created https://github.com/jaakkopasanen/AutoEq/issues/494 where we can keep talking about the progress of the work on the upgrade.

**Comment by jaakkopasanen** [comment]
I have been reworking the parametric eq optimizer using SciPy's minimize function. The minimize function runs faster than my Tensorflow implementation and I've added extra optimizations on top. Getting rid of Tensorflow also fixes the memory issues. I can now run with all cores and am getting about 80x speedup compared to old Tensorflow running on single core.

I'll be merging the branch to master soon.

Thanks again for your contribution! Really appreciate it.

**Comment by douglascamata** [comment]
@jaakkopasanen awesome! This sounds amazing. I'm very happy I could help and that you achieved this huge improvement. 💪

**Pull request merged**
